# Generated by Django 4.2 on 2024-11-25 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('url', models.URLField(verbose_name='لینک بنر')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='تصویر بنر')),
                ('position', models.CharField(choices=[('product_list', 'لیست محصولات'), ('home', 'صفحه اصلی')], max_length=200, verbose_name='موقعیت بنر')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='تصویر محصول')),
                ('short_description', models.CharField(db_index=True, default=None, max_length=400, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(default=None, max_length=500, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='برند')),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', max_length=300, verbose_name='عنوان دسته بندی')),
                ('title_url', models.CharField(db_index=True, default='', max_length=300, verbose_name='عنوان دسته بندی لاتین')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='VisitedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=30, verbose_name='آیپی کاربر')),
                ('visited_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازدید')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.product', verbose_name='محصول')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر id')),
            ],
            options={
                'verbose_name': 'محصول بازدید شده',
                'verbose_name_plural': 'محصولات بازدید شده',
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, verbose_name='کپشن-تگ')),
                ('product_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.product', verbose_name='تگ محصول')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery', verbose_name='تصویر محصول')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_module.productbrand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='project_module.productcategory', verbose_name='دسته بندی'),
        ),
    ]
